account_id = "2488ea57494b2dacae95a6e363e7dcb2"
name = "discord_stripe_store"
compatibility_date = "2024-07-22"
compatibility_flags = ["nodejs_compat_v2"]
send_metrics = true

assets = { directory = "public" }

[env.dev]
workers_dev = true
compatibility_date = "2024-07-22"
kv_namespaces = [
  { binding = "DISCORD_STRIPE_STORE", id = "9281e5515d1642e3b28eb59d0a0adaea" },
]

r2_buckets = [
  { binding = "DISCORD_STRIPE_BUCKET", bucket_name = "discord-stripe-bucket-dev" },
]

d1_databases = [
  { binding = "DB", database_name = "discord-stripe-database-dev", database_id = "babd696f-8e17-4611-a777-d6e9eff4561e", migrations_dir = "prisma/migrations" },
]

# [env.prod]
# workers_dev = false
# compatibility_date = "2024-07-22"
# kv_namespaces = [
#   { binding = "DISCORD_STRIPE_STORE", id = "9281e5515d1642e3b28eb59d0a0adaea" },
# ]

# r2_buckets = [
#   { binding = "DISCORD_STRIPE_BUCKET", bucket_name = "discord-stripe-bucket-dev" },
# ]

# d1_databases = [
#   { binding = "DB", database_name = "discord-stripe-database-dev", database_id = "babd696f-8e17-4611-a777-d6e9eff4561e" },
# ]

[dev]
ip = "0.0.0.0"
port = 8787

[observability.logs]
enabled = true
