name = "discord_stripe_store"
compatibility_date = "2024-07-22"
send_metrics = true

[[env.production]]
account_id = { env = "CLOUDFLARE_ACCOUNT_ID" }
workers_dev = false
compatibility_date = "2024-07-22"
route = "yourdomain.com/*"

[[env.development]]
account_id = { env = "CLOUDFLARE_ACCOUNT_ID" }
workers_dev = true
compatibility_date = "2024-07-22"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
